export type {
  WorkspaceConfig,
  ServerDeclaration,
  ServerMap,
  ServerName,
  ClientTarget,
  GitHubSettings,
  GcpSettings,
  TerraformSettings,
  AtlassianSettings,
  WorkflowHints,
  KnownWorkflowHints,
  TerraformWorkflowHints,
  GitHubWorkflowHints,
  GcpWorkflowHints,
  AtlassianWorkflowHints,
  InstructionPreferences,
  LocalConfig,
  ProviderIdentities,
  KnownProviderIdentities,
  GitHubIdentity,
  GcpIdentity,
  TerraformIdentity,
  AtlassianIdentity,
} from "./domain/manifest.js";
export { DEFAULT_CONFIG, DEFAULT_LOCAL_CONFIG } from "./domain/manifest.js";

export {
  loadConfig,
  loadLocalConfig,
  writeLocalConfig,
  getConfigPath,
  getLocalConfigPath,
  CONFIG_FILE,
  LOCAL_CONFIG_FILE,
} from "./config-loader.js";

export {
  checkAuth,
  checkGitHubAuth,
  checkGcpAuth,
  checkTerraformAuth,
  checkAtlassianAuth,
  registerAuthChecker,
  listGitHubAccounts,
  listGcpAccounts,
  extractPinnableIdentity,
  resolveTokens,
  resolveTerraformEmail,
  checkDockerAvailable,
  type AuthStatus,
  type AuthChecker,
  type DockerStatus,
  type ProviderAccount,
  type ResolvedTokens,
} from "./auth-checker.js";

export {
  getServerDefaults,
  isKnownServer,
  shouldSkipDiagnostic,
  serverUsesDocker,
  type McpServerEntry,
  type McpServerDefaults,
} from "./domain/server-registry.js";

export {
  updateGitignore,
  upsertGitignoreSection,
  BEGIN_MARKER as GITIGNORE_BEGIN_MARKER,
  END_MARKER as GITIGNORE_END_MARKER,
  MANAGED_ENTRIES as GITIGNORE_MANAGED_ENTRIES,
} from "./gitignore.js";

export {
  TOOLKIT_PREFIX,
  CODEX_TOOLKIT_PREFIX,
  buildMcpServers,
  buildCursorServers,
  mergeMcpConfig,
  mergeCursorConfig,
  generateCursorConfig,
  writeCursorConfig,
  generateClaudeCodeConfig,
  writeClaudeCodeConfig,
  buildCopilotServers,
  mergeCopilotConfig,
  generateCopilotConfig,
  writeCopilotConfig,
  buildCodexServers,
  mergeCodexConfig,
  generateCodexConfig,
  writeCodexConfig,
  generateGeminiConfig,
  writeGeminiConfig,
  verifyClientConfig,
  extractEmbeddedTokens,
  type McpConfig,
  type McpUrlEntry,
  type CursorMcpConfig,
  type ConfigFileResult,
  type CopilotMcpConfig,
  type CopilotServerEntry,
  type CopilotStdioServer,
  type CopilotHttpServer,
  type CopilotInput,
  type CodexConfig,
  type CodexServerEntry,
  type CodexHttpServer,
  type VerificationEntry,
  type VerificationResult,
} from "./config-generator.js";

export {
  CLIENT_CLI_SPECS,
  checkCliAvailable,
  spawnCli,
  diagnosticServerNames,
  buildDiagnosticPrompt,
  runDiagnostic,
  buildValidationPrompt,
  runValidation,
  runClientDiagnostic,
  extractJson,
  type ClientCliSpec,
  type CliAvailability,
  type DiagnosticToolResult,
  type ClientDiagnosticResult,
  type DiagnosticDataCallback,
  type SpawnCliResult,
} from "./client-diagnostic.js";

export {
  buildInstructionPrompt,
  generateLlmInstructions,
  deriveInterToolChains,
  type InterToolChain,
} from "./instruction-generator.js";

export {
  upsertFencedSection,
  generateInstructions,
  writeInstructions,
  generateCursorInstructions,
  writeCursorInstructions,
  generateClaudeCodeInstructions,
  writeClaudeCodeInstructions,
  generateCopilotInstructions,
  writeCopilotInstructions,
  generateCodexInstructions,
  writeCodexInstructions,
  generateGeminiInstructions,
  writeGeminiInstructions,
  INSTRUCTION_TARGETS,
  BEGIN_MARKER as INSTRUCTION_BEGIN_MARKER,
  END_MARKER as INSTRUCTION_END_MARKER,
  type InstructionTarget,
} from "./instruction-writer.js";
